title: nitrologic archives
description: Root pages for local software resarch
baseurl: ""
url: "https://nitrologic.github.io"
author:
  name: Simon Armstrong

show_header: false
plugins:
  - jekyll-seo-tag
github:
  is_project_page: false  # Prevents GitHub repo link
seo:
  exclude_from_sitemap: true  # Optional: Keeps page lean
permalink: pretty
